name: AWS 疎通確認
on:
  workflow_dispatch:

jobs:
  describe_regions:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1

    - name: Run AWS CLI commands
      run: |
        aws ec2 describe-regions
